profile_data = {
    'reg_date': 'Дата регистрации',
    'name': 'ФИО',
    'sex': 'Пол',
    'born_date': 'Дата рождения',
    'residence': 'Место жительства',
    'education': 'Образование',
    'course': 'Курс',
    'profession': 'Специализация',
    'salary': 'Минимальная оплата в час',
    'hard_work': 'Тяжелый труд',
    'mid_work': 'Средне сложный труд',
    'art_work': 'Творческая работа',
    'other_work': 'Другие работы',
    'tools': 'Инструменты',
    'language': 'Языки',
    'phone': 'Телефон',
    'email': 'Почта',
    'citizenship': 'Гражданство',
    'wallet': 'Номер карты',
    'is_driver': 'Есть права',
    'transport': 'Транспорт',
    'is_military': 'Служил',
    'other_info': 'Дополнительная информация',
}
